server:
  port: '8082'

spring:
  profiles:
    active: qa

welcome:
  message: Welcome to Coding fun!!

---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: root1sonu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: root1sonu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: root1sonu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

